/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Payright } from "./Payright";
export * as factories from "./factories";
export { Payright__factory } from "./factories/Payright__factory";
